using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace CompassEx.Generator
{
    [Generator]
    public class LicenseWatermarkGenerator : ISourceGenerator
    {
        // 全部单行，不带任何换行符，杜绝断行语法错乱
        private const string ShortLicense = "Copyright (c) 2026 [Jockeyvb]. All rights reserved. Licensed AGPLv3, commercial license required. Contact: Jockeyvb@gmail.com / WeChat: Jockeyvb1";

        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public void Execute(GeneratorExecutionContext context)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("//------------------------------------------------------------------------------\n");
            sb.Append("// <auto-generated>\n");
            sb.Append("// License Watermark Embedded In DLL\n");
            sb.Append("// </auto-generated>\n");
            sb.Append("//------------------------------------------------------------------------------\n");
            sb.Append("namespace CompassEx\n");
            sb.Append("{\n");
            sb.Append("    public static class LicenseWatermark\n");
            sb.Append("    {\n");
            sb.Append("        public const string Notice = \"");
            sb.Append(ShortLicense.Replace("\"", "\"\""));
            sb.Append("\";\n");
            sb.Append("    }\n");
            sb.Append("}\n");

            string output = sb.ToString();
            context.AddSource("LicenseWatermark.g.cs", SourceText.From(output, Encoding.UTF8));
        }
    }
}