// <auto-generated> This file has been auto generated by EF Core Power Tools (Dapper OOP Advanced Single/Col Template). </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Dapper;
using Dapper.Contrib.Extensions;

namespace CompassEx.Data.Models
{
    [Dapper.Contrib.Extensions.Table("tbl_PersonEightWord")]
    public partial class TblPersonEightWord
    {
        [Dapper.Contrib.Extensions.Key]
        public string PersonEightWordId { get; set; }

        public string PersonId { get; set; }

        public DateTime? NowDate { get; set; }

        public string OldDate { get; set; }

        public string SkyLoc { get; set; }

        public DateTime CreateTime { get; set; }

        public DateTime? ChangeTime { get; set; }

        public string Name { get; set; }

        public string Info { get; set; }

        public string Question { get; set; }

        public int IsInvite { get; set; }

        public int InvitePoint { get; set; }

        public int IsFinished { get; set; }

        public int IsUploaded { get; set; }

        public DateTime? AsyncTime { get; set; }

        public string Other { get; set; }

        #region 💡 萬能自動 OOP 資料庫操作方法 (優化版 Active Record)

        /// <summary>
        /// 【OOP 靜態新增】將一個新物件直接寫入資料庫，並回傳新產生的自增 ID
        /// </summary>
        public static long Addnew(TblPersonEightWord entity)
        {
            if (entity == null) throw new ArgumentNullException(nameof(entity));
            
            using (IDbConnection db = CompassEx.Data.Comm.GetOpenConnection())
            {
                return db.Insert(entity);
            }
        }

        /// <summary>
        /// 【OOP 實例修改】根據當前物件的主鍵 [Key]，自動更新其他所有欄位資料
        /// </summary>
        public bool Update()
        {
            using (IDbConnection db = CompassEx.Data.Comm.GetOpenConnection())
            {
                return db.Update(this);
            }
        }

        /// <summary>
        /// 【OOP 實例刪除】根據當前物件的主鍵 [Key]，直接從資料庫移除此筆資料
        /// </summary>
        public bool Delete()
        {
            using (IDbConnection db = CompassEx.Data.Comm.GetOpenConnection())
            {
                return db.Delete(this);
            }
        }

        #endregion

        #region 💡 萬能進階動態查詢方法 (單個與集合分離)

        /// <summary>
        /// 【OOP 精確單個查詢】獲取符合條件的單個實體對象（只取符合條件的第一筆）
        /// </summary>
        /// <param name="where">篩選條件字典 (Key為欄位名, Value為比對值)</param>
        /// <param name="orderBy">排序欄位陣列 (例如: new[] { "GoodDayID DESC" })</param>
        public static TblPersonEightWord GetTblPersonEightWord(Dictionary<string, object> where = null, string[] orderBy = null)
        {
            // ⚡ 完美符合您的邏輯：回傳單個對象。傳入 (1, 1) 在底層精確限制 LIMIT 1 OFFSET 0
            var list = GetTblPersonEightWordCol(where, orderBy, 1, 1);
           return list?.FirstOrDefault();
        }

        /// <summary>
        /// 【OOP 萬能集合查詢】獲取分頁資料，支援動態篩選與多欄位排序。當 pageIndex <= 0 時，分頁功能自動關閉，撈取全表全部數據。
        /// </summary>
        /// <param name="where">篩選條件字典 (Key為欄位名, Value為比對值)</param>
        /// <param name="orderBy">排序欄位陣列 (例如: new[] { "GoodDayID DESC" })</param>
        /// <param name="pageIndex">目前頁碼 (從 1 開始計算，小於等於 0 則自動關閉分頁提取全表)</param>
        /// <param name="pageSize">每頁顯示筆數</param>
        public static List<TblPersonEightWord> GetTblPersonEightWordCol(Dictionary<string, object> where = null, string[] orderBy = null, int pageIndex = 0, int pageSize = 10)
        {
            var p = new DynamicParameters();
            var sqlBuilder = new System.Text.StringBuilder();
            
            // 基礎 SQL 語句
            sqlBuilder.Append("SELECT * FROM [tbl_PersonEightWord] WHERE 1=1");

            // 1. 全自動參數化拼接 WHERE 條件，100% 防注入
            if (where != null && where.Count > 0)
            {
                foreach (var item in where)
                {
                    sqlBuilder.Append($" AND [{item.Key}] = @{item.Key}");
                    p.Add(item.Key, item.Value);
                }
            }

            // 2. 全自動拼接多欄位排序
            if (orderBy != null && orderBy.Length > 0)
            {
                sqlBuilder.Append(" ORDER BY " + string.Join(", ", orderBy));
            }

            // 3. 精準分頁控制：只有當 pageIndex > 0 時才拼接 SQLite 分頁語法
            if (pageIndex > 0 && pageSize > 0)
            {
                sqlBuilder.Append($" LIMIT {pageSize} OFFSET {(pageIndex - 1) * pageSize}");
            }

            // 4. 呼叫連線執行
            using (IDbConnection db = CompassEx.Data.Comm.GetOpenConnection())
            {
                return db.Query<TblPersonEightWord>(sqlBuilder.ToString(), p).ToList();
            }
        }

        #endregion
    }
}
